Update sources

diff --git a/sources b/sources
--- a/sources
+++ b/sources
@@ -1,33 +1,53 @@
 #!/bin/bash
 
-# Define the path to the sources.list file
+# File path
 SOURCE_LIST="/etc/apt/sources.list"
 
-# Check if the sources.list file exists
-if [ -f "$SOURCE_LIST" ]; then
-    # Remove the existing sources.list file
-    rm -f "$SOURCE_LIST"
-fi
+# Exit if error
+handle_error() {
+    echo "Error: $1"
+    exit 1
+}
 
-# Create "Custom" sources.list
-cat <<EOL > "$SOURCE_LIST"
-deb https://fasttrack.debian.net/debian-fasttrack/ bookworm-fasttrack main contrib non-free
+# Update
+sudo apt-get update 
+
+# Install
+echo "Installing....................."
+sudo apt-get -y install fasttrack-archive-keyring gnupg2 lsb-release dpkg-dev fakeroot
+sudo apt-get -y install build-essential linux-headers-$(uname -r) dkms devscripts
+
+# VirtualBox key
+echo "Downloading and adding VirtualBox key..."
+wget -O- -q https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor -o /usr/share/keyrings/oracle_vbox_2016.gpg || handle_error "Failed to download and add VirtualBox GPG key."
+
+
+echo "Out with the old in with the new. Creating the new sources.list"
+
+# Delete existing sources.list
+sudo rm -f "$SOURCE_LIST"
+sleep 1
+
+# Create the new sources.list
+sudo bash -c "cat <<EOL > \"$SOURCE_LIST\"
+deb https://fasttrack.debian.net/debian-fasttrack/ main contrib non-free
+deb https://fasttrack.debian.net/debian-fasttrack/ bookworm-backports-staging main contrib non-free
 deb https://ftp.debian.org/debian/ bookworm contrib main non-free non-free-firmware
 deb https://ftp.debian.org/debian/ bookworm-updates contrib main non-free non-free-firmware
 deb https://ftp.debian.org/debian/ bookworm-proposed-updates contrib main non-free non-free-firmware
 deb https://ftp.debian.org/debian/ bookworm-backports contrib main non-free non-free-firmware
 deb https://deb.debian.org/debian-security bookworm-security contrib main non-free-firmware
-EOL
+deb [arch=amd64 signed-by=/usr/share/keyrings/oracle_vbox_2016.gpg] http://download.virtualbox.org/virtualbox/debian bookworm contrib
+EOL" || handle_error "Failed to create the sources.list file."
 
-# Add VirtualBox repo and key
-wget -O- -q https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmour -o /usr/share/keyrings/oracle_vbox_2016.gpg
-echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle_vbox_2016.gpg] http://download.virtualbox.org/virtualbox/debian bookworm contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
+echo "sources.list created successfully."
 
-# Update 
-sudo apt-get update
+# Update
+echo "Updating APT package index..."
+sudo apt-get update 
 
+# Upgrade 
+echo "Upgrading packages..."
+sudo apt-get -y upgrade
 
-
-# Done
-echo "The APT sources lists have been updated successfully."
-echo "Please log out and log back in for the group membership change to take effect."
+echo "Done"
